server:
  port: 8000
  servlet:
    context-path: '/'
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:h2db
    #url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
